### ISSUE TITLE
add email notification

### ISSUE THREAD

**Issue by aliceinwire** [aliceinwire/Gentoo_kernelCI#30]

**Comment by aliceinwire** [comment]
The point of sending email is to show what went wrong only on failure and reporting it to the gentoo-kernel mailing list.
Would be nice to work toward it.

**Comment by mjeveritt** [comment]
I'm thinking we'll set up a gmail address to (ab)use for this purpose, unless we can get a generic email from Infra... What do you think @aliceinwire ?

**Comment by aliceinwire** [comment]
in progress

**Comment by aliceinwire** [comment]
fixing with pull request #79

**Comment by aliceinwire** [comment]
better dealing with passwords http://docs.buildbot.net/latest/manual/secretsmanagement.html#secretmanagement

**Comment by aliceinwire** [comment]
email notification is been used for few months
