### ISSUE TITLE
buildbot worker script dependency checker

### ISSUE THREAD

**Issue by aliceinwire** [aliceinwire/Gentoo_kernelCI#50]
Looks like we need some dependency installer for make buildbot worker work, maybe we can make in the future a script for checking for unsatisfied dependency and install it automatically.
The dependency are also different from python 2 and python 3

**Comment by rajula96reddy** [comment]
Hey @aliceinwire do you mean checking if the required packages for buildbot worker are installed or not? If so, is it basically something similar to checking the installation of the following
``` 
pip install buildbot-worker
```
If not, can you please elaborate

**Comment by mjeveritt** [comment]
Pretty sure this means the packages/modules required by the worker process - not the actual worker itself @rajula96reddy .

**Comment by aliceinwire** [comment]
currently fixed by moving everything to docker
