### ISSUE TITLE
ValueError: unsupported pickle protocol: 3

### ISSUE THREAD

**Issue by mjeveritt** [aliceinwire/Gentoo_kernelCI#65]
`<kuzetsa> stdio log from buildbot job 899`

[build log](http://kernel1.amd64.dev.gentoo.org:8010/api/v2/logs/7305/raw)

**Comment by mjeveritt** [comment]
Appears to be a case of [this](https://stackoverflow.com/questions/25843698/valueerror-unsupported-pickle-protocol-3-python2-pickle-can-not-load-the-file)

**Comment by mjeveritt** [comment]
I believe this is fixed by using python3 throughout the worker processes. Self-assigning to check the current build sets for any remaining glitches.

**Comment by aliceinwire** [comment]
closing as fixed
